### PR TITLE
Updated logger to support MVVMCross 8

### PR DESCRIPTION
**Pull request by frankfolsche**
Hi I've attempted to update the project to MVVMCross 8 so it can be used with the latest version. 

Also mentioned in bug:  #524 

The update to the plugin is straight forward, but I can't seem to get the iOS example project running. I did run against a different project and it was able to starts where as before it was throwing errors.

As for backwards compatibility, it will not break if you use it targeting mvx 7, but it will not use the IMvxLog.

### CODE REVIEW

**Review by philvbprogrammer — APPROVED** [review]

**Comment by LeszekPieczaba** [comment]
Hi,
I would like to ask if this change will be available in a future either stable or pre release version of nuget package?

Thanks.

**Comment by frankfolsche** [comment]
@philvbprogrammer Thanks for approving my changes, but for some reason the PR got closed. Can you merge this and create a new release of the package?

**Comment by janusw** [comment]
> but for some reason the PR got closed.

From over here it looks like it got closed because you closed it ;)
(may have been accidental, I guess?)


> Can you merge this and create a new release of the package?

In principle it would be great to get this into master (and a new release), but right now I can see two hurdles:
1) There are conflicts in BLE.Client. Those should be fixed first by either merging the current master into your branch or (maybe preferable) rebasing your branch on current master.
2) You mention in the original comment that the iOS sample is not running. This should be fixed as well. What exactly happens when the sample starts up?

Once both of these have been dealt with, this can hopefully be merged.

**Comment by frankfolsche** [comment]
@janusw thanks for the reply, I've resolved the merge conflicts. 
I will have a look at the iOS and MacOs Samples soon.

**Comment by frankfolsche** [comment]
> 

I've confirmed that the sample app starts and I scan for devices on Android, iOS, UWP and macOS.

Let me know if there is anything else.

**Comment by janusw** [comment]
> @janusw thanks for the reply, I've resolved the merge conflicts.

> I've confirmed that the sample app starts and I scan for devices on Android, iOS, UWP and macOS.

Awesome, thanks! Please give me a few days to have a look at this ...

**Review by janusw — APPROVED** [review]
LGTM!

**Comment by janusw** [comment]
Thanks for the contribution!

**Comment by janusw** [comment]
@frankfolsche One belated review item that I missed earlier: I just noticed that the MvvmCross version in MvvmCross.Plugins.BLE.UWP was apparently not updated. Could you maybe take care of that in a follow-up PR?

**Comment by frankfolsche** [comment]
> @frankfolsche One belated review item that I missed earlier: I just noticed that the MvvmCross version in MvvmCross.Plugins.BLE.UWP was apparently not updated. Could you maybe take care of that in a follow-up PR?

Great news that it's merged I've created a new PR for UWP:
https://github.com/xabre/xamarin-bluetooth-le/pull/611

**Pull request merged**
