### PR TITLE
Update the Mvvmcross package to v6 and use Xamarin.Froms v2

### PR DESCRIPTION
**Pull request by flyingxu**
the MvvmCross package is updated to v6, for #301
-Navigation change
-plugin load change
-MvxContentPage change
-Log change
-Acr.UserDialogs change

The PLC projects are also updated to NetStandard 2 projects, partially addresses #285 . The files structure is not updated yet.

This PR use Xamarin.Forms v2.5 purposely, because XF v3.0 has a bug currently.

### CODE REVIEW

**Comment by smstuebe** [comment]
All this new stuff should be considered as 2.0.0.
We should create a branch for that, so we can introduce breaking changes. James did a new major release for the switch to netstandard, and I will do it, too for my fingerprint plugin.

**Comment by flyingxu** [comment]
Sure, I have no objection to that.

**Comment by xabre** [comment]
I'm assuming we can re-target the PR to 2.0.0

**Comment by smstuebe** [comment]
https://blog.nuget.org/20140924/supporting-semver-2.0.0.html
now, that nuget supports semver, finally, maybe `-pre.1` would have been the better choice :D

**Comment by xabre** [comment]
Good point. We can name the next one -pre1.1 :))

**Comment by flyingxu** [comment]
close this for a new PR to the branch of xabre:2.0.0

**Pull request closed without merging**
