### PR TITLE
Upgrade to Xamarin.Forms 3.2 and MvvmCross 6.2.1

### PR DESCRIPTION
**Pull request by flyingxu**
Upgrade to Xamarin.Forms 3.2, 
Upgrade to MvvmCross 6.2.1,

Other nuget packages are also updated.

### CODE REVIEW

**Comment by carolynbarbour** [comment]
Keen to get an update to this package with this PR included :)

Much appreciated work @flyingxu

**Comment by flyingxu** [comment]
@carolynbarbour I merged this PR.
I'm just curious, are you using the v1.3 or the v2.0-pre?

**Comment by carolynbarbour** [comment]
@flyingxu I was trying to implement v2.0-pre but the plugin failed to load and I presumed it was due to a mismatch of mvvmcross versions. If you've got any other ideas, the only two things that came to mind was to upgrade mvvmcross 6.2.1 and check if it works or to pull this project and implement it locally to debug through the initialisation process.

**Comment by flyingxu** [comment]
@carolynbarbour 
I can't release the nuget package so I am using the locally compiled package. 
I will create another PR to share how I pack the nuget package and use it. I'm using the 2.0 branch without any problem.

**Comment by carolynbarbour** [comment]
@flyingxu That'd be a great help. Thanks 👍

**Comment by flyingxu** [comment]
@carolynbarbour Please check the PR of #332

**Comment by carolynbarbour** [comment]
@flyingxu Thanks for this. Much appreciated

**Pull request merged**
