### PR TITLE
updated UWP plugin to support mvvmcross 8.

### PR DESCRIPTION
**Pull request by frankfolsche**
Added support for MVVMCross and UWP

### CODE REVIEW

**Comment by frankfolsche** [comment]
I've pushed the missing package update, if it's needed to rebase/merge with master let me know, but it should be fine.

**Review by janusw — APPROVED** [review]
Thanks for the update. LGTM!

**Comment by janusw** [comment]
> if it's needed to rebase/merge with master let me know, but it should be fine.

Not necessary, but for the next PR, please update your master first and branch from there ;)

**Comment by janusw** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
