### PR TITLE
Feature/additional scan filtering

### PR DESCRIPTION
**Pull request by AdamDiament**
* Adds scan filters for manufacturerid and mac address to android scanning
* Updates the sample app with a new filtered scan tab
* Added instructions to the readme

### CODE REVIEW

**Comment by AdamDiament** [comment]
@janusw do you know when you might be able to have a look at merging this one or suggesting edits? No pressure but it would be useful to know, just so I can decide if I should integrate my forked version into my application or if I can wait until review. Thanks!

**Comment by janusw** [comment]
Hi @AdamDiament,
I'm currently on an island in the sun without my laptop, but I should be able to have a look at this within a week or so.

**Comment by AdamDiament** [comment]
> Hi @AdamDiament, I'm currently on an island in the sun without my laptop, but I should be able to have a look at this within a week or so.

Ok thanks for getting back to me, that'll be fine. [Here's some beach music.](https://www.youtube.com/watch?v=erG5rgNYSdk&ab_channel=WeezerVEVO)

**Comment by janusw** [comment]
Glad you got the Weezer reference 😆

**Review by janusw — COMMENTED** [review]
Hi Adam,
I managed to have a first look at your changes, and it all looks very solid to me. Thanks for your contribution!

Two minor comments:
* You're breaking the API by changing the `IAdapter` interface. Maybe it would be worth to keep the old variant of `StartScanningForDevicesAsync` for backward compatibility? You're already doing this in the `AdapterExtensions`, but not in the adapter interface itself. All your changes to the native methods (`StartScanningForDevicesNativeAsync`) are ok, since those are protected.
* As your todo comments document, your scan-filtering API does not cover all of the options offered by Android (yet). What I'm missing in particular is filtering on service data. We can leave that as a follow-up, of course. Or do you plan to still add the missing stuff to this PR?

**Comment by AdamDiament** [comment]
> * You're breaking the API by changing the `IAdapter` interface. Maybe it would be worth to keep the old variant of `StartScanningForDevicesAsync` for backward compatibility? You're already doing this in the `AdapterExtensions`, but not in the adapter interface itself. All your changes to the native methods (`StartScanningForDevicesNativeAsync`) are ok, since those are protected.

Good plan. I added a commit that re-adds the overload you suggest to keep the api backwards compatible.

> As your todo comments document, your scan-filtering API does not cover all of the options offered by Android (yet). What I'm missing in particular is filtering on service data. We can leave that as a follow-up, of course. Or do you plan to still add the missing stuff to this PR?

I was planning to leave these more complex scan filtering options for a future PR, if that's ok.

> On the topic of service data filtering - do you know what exactly it is for or could point to some documentation? Android docs are not much help!  I am wondering if it is for connectable/pairable devices only and does some kind of preliminary "getservices" query as part of the scan before returning the advertising data. Or is it just filtering on what is already available in the packet. All the non-pairable beacons I work with return null for service UUID, so I have resorted to scan filtering by macaddress/manufacturer id I'm interested to know if I would be able to use service data filtering in any way, or if it's just not relevant for these kind of devices.

**Comment by janusw** [comment]
> > * You're breaking the API by changing the `IAdapter` interface. Maybe it would be worth to keep the old variant of `StartScanningForDevicesAsync` for backward compatibility? You're already doing this in the `AdapterExtensions`, but not in the adapter interface itself. All your changes to the native methods (`StartScanningForDevicesNativeAsync`) are ok, since those are protected.
> 
> Good plan. I added a commit that re-adds the overload you suggest to keep the api backwards compatible.

Awesome, thanks!

> > As your todo comments document, your scan-filtering API does not cover all of the options offered by Android (yet). What I'm missing in particular is filtering on service data. We can leave that as a follow-up, of course. Or do you plan to still add the missing stuff to this PR?
> 
> I was planning to leave these more complex scan filtering options for a future PR, if that's ok.

Yeah, sure, fine with me. I can actually take care of adding the service-data filtering.

> On the topic of service data filtering - do you know what exactly it is for or could point to some documentation? Android docs are not much help! I am wondering if it is for connectable/pairable devices only and does some kind of preliminary "getservices" query as part of the scan before returning the advertising data. Or is it just filtering on what is already available in the packet.

The latter. IIUC it only filters on stuff in the advertising packet (as all the scan filters do). Of course there are different BLE advertising types, and the service data type is just one of them. Therefore the service-data filtering applies only to advertising packets that actually contain service data, and not to those that contain manufacturer-specific data, for example.

> All the non-pairable beacons I work with return null for service UUID, so I have resorted to scan filtering by macaddress/manufacturer id.

Could you give an example of what kind of non-pairable beacons you work with?

> I'm interested to know if I would be able to use service data filtering in any way, or if it's just not relevant for these kind of devices.

You need a device that advertises with service data, everything else will be filtered away when using a service-data filter.

**Comment by AdamDiament** [comment]
Thanks!

> Could you give an example of what kind of non-pairable beacons you work with?

 Lots of stuff by fieldpiece, including https://www.fieldpiece.com/product-category/manometers/

**Review by janusw — APPROVED** [review]
LGTM with your additions. Thanks again!

**Pull request merged**
