### PR TITLE
Extend the cake script and GH Actions build

### PR DESCRIPTION
**Pull request by janusw**
Build the sample projects (BLE.Client.*) in addition to the core libraries. Also split off the 'Clean' and 'Restore' parts into separate steps.

### CODE REVIEW

**Comment by janusw** [comment]
A strange error occurs in  the GH Actions build here, when building `BLE.Client.macOS` via cake:

```
MMP : error MM0007: The root assembly '/Users/runner/work/xamarin-bluetooth-le/xamarin-bluetooth-le/Source/BLE.Client/BLE.Client.macOS/bin/Release/BLE Sample.exe' does not exist
[/Users/runner/work/xamarin-bluetooth-le/xamarin-bluetooth-le/Source/BLE.Client/BLE.Client.macOS/BLE.Client.macOS.csproj]
```

I also see this when running cake locally (on a MacBook). However, `BLE.Client.macOS` builds and runs fine via VS for Mac. So maybe this is some sort of cake issue? Or does anyone have any other ideas?

**Comment by JanNepras** [comment]
@janusw Have you tried it on windows-latest? Could you please update pr description to make this pr more clear?

**Comment by janusw** [comment]
> @janusw Have you tried it on windows-latest?

Interestingly, this seems to work. Thanks for the suggestion. The error above seems to be a Mac-specific cake bug, I guess.

**Comment by janusw** [comment]
> Could you please update pr description to make this pr more clear?

Done. Sorry for being a bit sloppy.

If there are no further comments here, I'll merge this by tomorrow.

**Review by JanNepras — APPROVED** [review]
Looking good! In the future to remove warnings such as:

> Missing XML comment for publicly visible type or member 'Adapter'

could we add [inheritdoc](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc)?

**Comment by janusw** [comment]
> In the future to remove warnings such as:
> 
> > Missing XML comment for publicly visible type or member 'Adapter'
> 
> could we add [inheritdoc](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc)?

I guess so. If you'd like to contribute a PR which does that, that would be very welcome ...

**Pull request merged**
