### PR TITLE
Fix Android autoConnect flag

### LINKED ISSUE #182: Autoconnect on Android
Investigate and document the behaviour of Android the auto-connect flag.

### PR DESCRIPTION
**Pull request by Hoidi**
Resolves #182 

Basically only closes the gatt instance when autoConnect was set to false when connecting to that device

### CODE REVIEW

**Comment by ske66** [comment]
Incredible. I just found this bug 30 minutes ago and there's already a fix. Brilliant work!

**Comment by Hoidi** [comment]
@xabre Would you mind taking a look at this?

**Comment by Hoidi** [comment]
@janusw Any opinions on this?

**Review by janusw — APPROVED** [review]
This essentially looks ok to me (only the `GetConnectParameters` property could be slightly simplified).

Sorry that it took so long to review this!

**Comment by Khadeeja-Madathil** [comment]
After setting auto connect to true for Android devices, ConnectToKnownDeviceAsync always gives TaskCanceledException. Works fine on removing the autoconnect flag.

**Pull request merged**
